"""empty message

Revision ID: 4a5f71cf7870
Revises: d18d68c1a65c
Create Date: 2020-08-02 15:09:53.765461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a5f71cf7870'
down_revision = 'd18d68c1a65c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LinRegResults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('YearsExperience', sa.Float(), nullable=True),
    sa.Column('Prediction', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('public.LinRegResults')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public.LinRegResults',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"public.LinRegResults_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('YearsExperience', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Prediction', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='public.LinRegResults_pkey')
    )
    op.drop_table('LinRegResults')
    # ### end Alembic commands ###
