"""empty message

Revision ID: d18d68c1a65c
Revises: 
Create Date: 2020-08-02 14:47:40.049401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18d68c1a65c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public.LinRegResults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('YearsExperience', sa.Float(), nullable=True),
    sa.Column('Prediction', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public.LinRegResults')
    # ### end Alembic commands ###
